
SuperColliderSuperCollider

7SuperColliderProToolsSuperCollider 17SuperCollider 3

SuperColliderSuperColliderSuperCollider

3SuperColliderSuperCollider2SuperColloder

////////////////////////////////////////////////////////////////////////////////////////////////////

-Mark Polishook, DSP SuperSchool, Ogaki City, Japan, February, 2004
polishoo@cwu.edu
polishoo@daimi.au.dk



kotobuki@yapan.org


