LinExp convert a linear range to an exponential range

LinExp.ar(in, srclo, srchi, dstlo, dsthi)
LinExp.kr(in, srclo, srchi, dstlo, dsthi)

Converts a linear range of values to an exponential range of values.
The dstlo and dsthi arguments must be nonzero and have the same sign.
in - input to convert.
srclo - lower limit of input range.
srchi - upper limit of input range.
dstlo - lower limit of output range.
dsthi - upper limit of output range.


