resize


resize behavior for SCView


 1 2 3
 4 5 6
 7 8 9
 
 1 - fixed to left, fixed to top
 2 - horizontally elastic, fixed to top
 3 - fixed to right, fixed to top
 
 4 - fixed to left, vertically elastic
 5 - horizontally elastic, vertically elastic
 6 - fixed to right, vertically elastic
 
 7 - fixed to left, fixed to bottom
 8 - horizontally elastic, fixed to bottom
 9 - fixed to right, fixed to bottom
 
