
Getting Started With SuperCollider

by Scott Wilson


Table of Contents

In OSX click on the links below to take you to the corresponding document.

To Begin

	Introductory Remarks
	First Steps

Making Sound

	Start Your Engines
	Functions and Other Functionality
	Functions and Sound
	Presented in Living Stereo
	Mix it Up
	Scoping and Plotting
	
	Getting Help
	
Server Abstractions

	SynthDefs and Synths
	Busses
	Groups
	Buffers
	




