Spec specification of an input datatype

This is an abstract class. Specs specify what kind of input is required or permissible, and what the range of those parameters are.

common subclasses:
 AudioSpec
 ControlSpec
 ScalarSpec


Spec has subclasses which depict different kinds of possible inputs.
This is of interest to functions, to gui interface objects (sliders etc.) and others.

The class Spec itself holds a master Dictionary of common specifications. 




